[build]
buildCommand = "bash build.sh"

[deploy]
startCommand = "python manage.py migrate --noinput && python manage.py collectstatic --noinput --clear && gunicorn checkia.wsgi:application --bind 0.0.0.0:$PORT"
